export const NANKAI_LINE_STATIONS = {
  '1': { kind: 'start',         lineKind: 'nankai',         signal: '',             lineSwitch: true  , name: 'namba'},
  '2': { kind: 'normal',        lineKind: 'nankai',         signal: '',             lineSwitch: true  , name: 'shinimamiya'},
  '3': { kind: 'normal',        lineKind: 'nankai',         signal: '',             lineSwitch: true  , name: 'tengachaya'},
  '4': { kind: 'normal',        lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'kishinosatotamade'},
  '5': { kind: 'normal',        lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'kohama'},
  '6': { kind: 'normal',        lineKind: 'nankai',         signal: '',             lineSwitch: true  , name: 'sumiyoshitaisha'},
  '7': { kind: 'normal',        lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'suminoe'},
  '8': { kind: 'normal',        lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'shichido'},
  '9': { kind: 'normal',        lineKind: 'nankai',         signal: 'is-partSignal',  lineSwitch: false , name: 'sakai'},
  '10': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'minato'},
  '11': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'ishizugawa'},
  '12': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'suwanomori'},
  '13': { kind: 'normal',       lineKind: 'nankai',         signal: '',             lineSwitch: true  , name: 'hamaderakoen'},
  '14': { kind: 'transfer',     lineKind: 'nankai',         signal: '',             lineSwitch: true  , name: 'hagoromo'},
  '15': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'takaishi'},
  '16': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'kitasukematsu'},
  '17': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'matsunohama'},
  '18': { kind: 'normal',       lineKind: 'nankai',         signal: 'is-partSignal',  lineSwitch: false , name: 'izumiotsu'},
  '19': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'tadaoka'},
  '20': { kind: 'normal',       lineKind: 'nankai',         signal: 'is-partSignal',  lineSwitch: false , name: 'haruki'},
  '21': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'izumiomiya'},
  '22': { kind: 'normal',       lineKind: 'nankai',         signal: 'is-partSignal',  lineSwitch: false , name: 'kishiwada'},
  '23': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'takojizo'},
  '24': { kind: 'normal',       lineKind: 'nankai',         signal: 'is-partSignal',  lineSwitch: true  , name: 'kaizuka'},
  '25': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'nishikinohama'},
  '26': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'tsuruhara'},
  '27': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'iharanosato'},
  '28': { kind: 'normal',       lineKind: 'nankai',         signal: '',             lineSwitch: false , name: 'izumisano'},
  '29': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'hagurazaki'},
  '30': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'yoshiminosato'},
  '31': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'okadaura'},
  '32': { kind: 'normal',       lineKind: 'nankai',         signal: '',             lineSwitch: false , name: 'tarui'},
  '33': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'ozaki'},
  '34': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'tottorinosho'},
  '35': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'hakotsukuri'},
  '36': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'tannowa'},
  '37': { kind: 'transfer',     lineKind: 'nankai',         signal: 'is-partSignal',  lineSwitch: false , name: 'misakikoen'},
  '38': { kind: 'normal',       lineKind: 'nankai',         signal: '',  lineSwitch: false , name: 'kyoshi'},
  '39': { kind: 'normal',       lineKind: 'nankai',         signal: '',             lineSwitch: false , name: 'wadaimae'},
  '40': { kind: 'kadaBranch',   lineKind: 'nankai',         signal: '',             lineSwitch: false , name: 'kinokawa'},
  '41': { kind: 'normal',       lineKind: 'nankai',     signal: '',             lineSwitch: true  , name: 'wakayamashi'},
  '42': { kind: 'branchEnd',    lineKind: 'wakayamako',     signal: '',             lineSwitch: false , name: 'wakayamako'},
  '43': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '44': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '45': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '46': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '47': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '48': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '49': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '50': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '51': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '52': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '53': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '54': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '55': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '56': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '57': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '58': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '59': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '60': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '61': { kind: 'start',        lineKind: 'takashinohama',  signal: 'is_nosignal',  lineSwitch: false , name: 'hagoromo'},
  '62': { kind: 'normal',       lineKind: 'takashinohama',  signal: 'is_nosignal',  lineSwitch: false , name: 'kyarabashi'},
  '63': { kind: 'branchEnd',    lineKind: 'takashinohama',  signal: 'is_nosignal',  lineSwitch: false , name: 'takashinohama'},
  '64': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '65': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '66': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '67': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '68': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '69': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '70': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '71': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '72': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '73': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '74': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '75': { kind: 'branchStart',  lineKind: 'kuko',           signal: '',             lineSwitch: false , name: ''},
  '76': { kind: 'normal',       lineKind: 'kuko',           signal: '',             lineSwitch: true  , name: 'rinkutown'},
  '77': { kind: 'branchEnd',    lineKind: 'kuko',           signal: '',             lineSwitch: true  , name: 'kansaiairport'},
  '78': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '79': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '80': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '81': { kind: 'start',        lineKind: 'tanagawa',       signal: 'is_nosignal',  lineSwitch: false , name: 'tanagawa'},
  '82': { kind: 'normal',       lineKind: 'tanagawa',       signal: 'is_nosignal',  lineSwitch: false , name: 'fukeko'},
  '83': { kind: 'normal',       lineKind: 'tanagawa',       signal: 'is_nosignal',  lineSwitch: false , name: 'fukecho'},
  '84': { kind: 'branchEnd',    lineKind: 'tanagawa',       signal: '',             lineSwitch: false , name: 'misakikoen'},
  '85': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '86': { kind: 'none',         lineKind: null,             signal: '',             lineSwitch: false , name: ''},
  '87': { kind: 'branchStart',  lineKind: 'kada',           signal: '',             lineSwitch: false , name: ''},
  '88': { kind: 'normal',       lineKind: 'kada',           signal: '',             lineSwitch: false , name: 'higashimatsue'},
  '89': { kind: 'normal',       lineKind: 'kada',           signal: '',             lineSwitch: false , name: 'nakamatsue'},
  '90': { kind: 'normal',       lineKind: 'kada',           signal: 'is_nosignal',  lineSwitch: false , name: 'hachimanmae'},
  '91': { kind: 'normal',       lineKind: 'kada',           signal: 'is_nosignal',  lineSwitch: false , name: 'nishinosho'},
  '92': { kind: 'normal',       lineKind: 'kada',           signal: '',             lineSwitch: false , name: 'nirigahama'},
  '93': { kind: 'normal',       lineKind: 'kada',           signal: '',             lineSwitch: false , name: 'isonoura'},
  '94': { kind: 'branchEnd',    lineKind: 'kada',           signal: '',             lineSwitch: false , name: 'kada'},
}

export const KOUYA_LINE_STATIONS = {
  '95': {kind: 'start',         lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'namba'},
  '96': {kind: 'normal',        lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'imamiyaebisu'},
  '97': {kind: 'normal',        lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'shinimamiya'},
  '98': {kind: 'normal',        lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'haginochaya'},
  '99': {kind: 'normal',        lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'tengachaya'},
  '100': {kind: 'transfer',     lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kishinosatotamade'},
  '101': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'tezukayama'},
  '102': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'sumiyoshihigashi'},
  '103': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'sawanocho'},
  '104': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'abikomae'},
  '105': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'asakayama'},
  '106': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'sakaihigashi'},
  '107': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'mikunigaoka'},
  '108': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'mozuhachiman'},
  '109': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'nakamozu'},
  '110': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'shirasagi'},
  '111': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'hatsushiba'},
  '112': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'hagiharatenjin'},
  '113': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kitanoda'},
  '114': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'sayama'},
  '115': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'osakasayamashi'},
  '116': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kongo'},
  '117': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'takidani'},
  '118': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'chiyoda'},
  '119': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'kawachinagano'},
  '120': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'mikkaichicho'},
  '121': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'mikanodai'},
  '122': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'chihayaguchi'},
  '123': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'amami'},
  '124': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kimitoge'},
  '125': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'rinkandenentoshi'},
  '126': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'miyukitsuji'},
  '127': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'hashimoto'},
  '128': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kiishimizu'},
  '129': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kamuro'},
  '130': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kudoyama'},
  '131': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'koyashita'},
  '132': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'shimokosawa'},
  '133': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kamikosawa'},
  '134': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kiihosokawa'},
  '135': {kind: 'normal',       lineKind: 'koya',         signal: '',             lineSwitch: false , name: 'kiikamiya'},
  '136': {kind: 'branchEnd',    lineKind: 'koya',         signal: '',             lineSwitch: true  , name: 'gokurakubashi'},
  '137': {kind: 'start',        lineKind: 'shiomibashi',  signal: 'is_nosignal',  lineSwitch: false , name: 'shiomibashi'},
  '138': {kind: 'normal',       lineKind: 'shiomibashi',  signal: 'is_nosignal',  lineSwitch: false , name: 'ashiharacho'},
  '139': {kind: 'normal',       lineKind: 'shiomibashi',  signal: 'is_nosignal',  lineSwitch: false , name: 'kizugawa'},
  '140': {kind: 'normal',       lineKind: 'shiomibashi',  signal: 'is_nosignal',  lineSwitch: false , name: 'tsumori'},
  '141': {kind: 'normal',       lineKind: 'shiomibashi',  signal: 'is_nosignal',  lineSwitch: false , name: 'nishitengachaya'},
  '142': {kind: 'branchEnd',    lineKind: 'shiomibashi',  signal: 'is_nosignal',  lineSwitch: false , name: 'kishinosatotamade'},
  '143': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '144': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '145': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '146': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '147': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '148': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '149': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '150': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '151': {kind: 'branchStart',  lineKind: 'senboku',      signal: '',             lineSwitch: false , name: 'nakamozu'},
  '152': {kind: 'normal',       lineKind: 'senboku',      signal: '',             lineSwitch: false , name: 'fukai'},
  '153': {kind: 'normal',       lineKind: 'senboku',      signal: '',             lineSwitch: false , name: 'izumigaoka'},
  '154': {kind: 'normal',       lineKind: 'senboku',      signal: '',             lineSwitch: false , name: 'toga_mikita'},
  '155': {kind: 'normal',       lineKind: 'senboku',      signal: '',             lineSwitch: false , name: 'komyoike'},
  '156': {kind: 'branchEnd',    lineKind: 'senboku',      signal: '',             lineSwitch: false , name: 'izumichuo'},
  '157': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '158': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '159': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '160': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '161': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '162': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '163': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '164': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '165': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '166': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '167': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '168': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '169': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '170': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '171': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '172': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '173': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '174': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '175': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '176': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '177': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
  '178': {kind: 'none',         lineKind: null,           signal: '',             lineSwitch: false , name: ''},
}

// tid-converter/db/fixtures/10_train_kind.rb と同一
export const TRAIN_KINDS = {
  '100': {id: 1,   line_id: 1, image_name: '', train_number: '00', train_type: '',              kind: '', section: ''},
  '200': {id: 1,   line_id: 2, image_name: '', train_number: '00', train_type: '',              kind: '', section: ''},
  '101': {id: 2,   line_id: 1, image_name: '', train_number: '01', train_type: '特急ラピートα',   kind: 'is_rapit', section: '難波～関西空港（ノンストップ）'},
  '201': {id: 3,   line_id: 2, image_name: '', train_number: '01', train_type: '特急天空',       kind: 'is_tenku', section: '橋本～極楽橋'},
  '102': {id: 4,   line_id: 1, image_name: '', train_number: '02', train_type: '特急ラピートβ',   kind: 'is_rapit', section: '難波～関西空港'},
  '202': {id: 5,   line_id: 2, image_name: '', train_number: '02', train_type: '特急泉北ライナー', kind: 'is_senboku', section: '難波～和泉中央'},
  '205': {id: 24,  line_id: 2, image_name: '', train_number: '05', train_type: 'GRAN 天空',      kind: 'is_gran_tenkuu', section: '難波～極楽橋'},
  '103': {id: 6,   line_id: 1, image_name: '', train_number: '03', train_type: '特急',           kind: 'is_rapit', section: '難波～和歌山市（全席指定）'},
  '104': {id: 7,   line_id: 1, image_name: '', train_number: '04', train_type: '特急',           kind: 'is_rapit', section: '難波～和歌山港（全席指定）'},
  '105': {id: 8,   line_id: 1, image_name: '', train_number: '05', train_type: '特急サザン',      kind: 'is_sazan', section: '難波～和歌山市（一部指定）'},
  '106': {id: 9,   line_id: 1, image_name: '', train_number: '06', train_type: '特急サザン',      kind: 'is_sazan', section: '難波～和歌山港（一部指定）'},
  '206': {id: 10,  line_id: 2, image_name: '', train_number: '06', train_type: '特急りんかん',    kind: 'is_rinkan', section: '難波～橋本'},
  '107': {id: 11,  line_id: 1, image_name: '', train_number: '07', train_type: '特急ラピートα',   kind: 'is_rapit', section: '難波～関西空港（途中一部停車）'},
  '207': {id: 12,  line_id: 2, image_name: '', train_number: '07', train_type: '特急',           kind: 'is_rapit', section: '難波～橋本（自由）'},
  '108': {id: 13,  line_id: 1, image_name: '', train_number: '08', train_type: '特急',           kind: 'is_rapit', section: '難波～和歌山市（自由）'},
  '208': {id: 14,  line_id: 2, image_name: '', train_number: '08', train_type: '特急こうや',      kind: 'is_koya', section: '難波～極楽橋'},
  '109': {id: 15,  line_id: 1, image_name: '', train_number: '09', train_type: '特急',           kind: 'is_rapit', section: '難波～和歌山港（自由）'},
  '209': {id: 16,  line_id: 2, image_name: '', train_number: '09', train_type: '特急',           kind: 'is_rapit', section: '難波・橋本～極楽橋'},
  '010': {id: 17,  line_id: 0, image_name: '', train_number: '10', train_type: '',               kind: '', section: ''},
  '011': {id: 18,  line_id: 0, image_name: '', train_number: '11', train_type: '',               kind: '', section: ''},
  '012': {id: 19,  line_id: 0, image_name: '', train_number: '12', train_type: '',               kind: '', section: ''},
  '013': {id: 20,  line_id: 0, image_name: '', train_number: '13', train_type: '',               kind: '', section: ''},
  '014': {id: 21,  line_id: 0, image_name: '', train_number: '14', train_type: '',               kind: '', section: ''},
  '015': {id: 22,  line_id: 0, image_name: '', train_number: '15', train_type: '',               kind: '', section: ''},
  '016': {id: 23,  line_id: 0, image_name: '', train_number: '16', train_type: '',               kind: '', section: ''},
  '117': {id: 24,  line_id: 1, image_name: '', train_number: '17', train_type: '急行',           kind: 'is_express', section: '難波～和歌山市'},
  '217': {id: 25,  line_id: 2, image_name: '', train_number: '17', train_type: '快速急行',        kind: 'is_rapit', section: '難波～橋本'},
  '118': {id: 26,  line_id: 1, image_name: '', train_number: '18', train_type: '急行',           kind: 'is_express', section: '難波～和歌山市'},
  '119': {id: 27,  line_id: 1, image_name: '', train_number: '19', train_type: '急行',           kind: 'is_express', section: '難波・和歌山市～和歌山港'},
  '219': {id: 28,  line_id: 2, image_name: '', train_number: '19', train_type: '快速急行',        kind: 'is_rapit', section: '難波～極楽橋'},
  '020': {id: 29,  line_id: 0, image_name: '', train_number: '20', train_type: '',               kind: '', section: ''},
  '121': {id: 30,  line_id: 1, image_name: 'train_airport_express', train_number: '21', train_type: '空港急行',        kind: 'is_kukoExpress', section: '難波～関西空港'},
  '122': {id: 31,  line_id: 1, image_name: 'train_airport_express', train_number: '22', train_type: '空港急行',        kind: 'is_kukoExpress', section: '難波～関西空港'},
  '123': {id: 32,  line_id: 1, image_name: '', train_number: '23', train_type: '急行',            kind: 'is_express', section: '難波～春木'},
  '124': {id: 33,  line_id: 1, image_name: 'train_izumisano_express', train_number: '24', train_type: '白線急行',        kind: 'is_izumisanoExpress', section: '難波～泉佐野'},
  '224': {id: 34,  line_id: 2, image_name: '', train_number: '24', train_type: '急行',            kind: 'is_express', section: '難波～三日市町'},
  '225': {id: 35,  line_id: 2, image_name: '', train_number: '25', train_type: '急行',            kind: 'is_express', section: '難波～林間田園都市'},
  '126': {id: 36,  line_id: 1, image_name: '', train_number: '26', train_type: '急行',            kind: 'is_express', section: '難波～みさき公園～（回送～和歌山市）'},
  '226': {id: 37,  line_id: 2, image_name: '', train_number: '26', train_type: '急行',            kind: 'is_express', section: '難波～林間田園都市～（回送～小原田信号所）'},
  '127': {id: 38,  line_id: 1, image_name: '', train_number: '27', train_type: '急行',            kind: 'is_express', section: '難波～和歌山市（春木停車）'},
  '227': {id: 39,  line_id: 2, image_name: '', train_number: '27', train_type: '急行',            kind: 'is_express', section: '難波～橋本'},
  '128': {id: 40,  line_id: 1, image_name: '', train_number: '28', train_type: '急行',            kind: 'is_express', section: '難波～和歌山市（春木停車）'},
  '228': {id: 41,  line_id: 2, image_name: '', train_number: '28', train_type: '急行',            kind: 'is_express', section: '難波～高野下'},
  '129': {id: 42,  line_id: 1, image_name: '', train_number: '29', train_type: '急行',            kind: 'is_express', section: '難波～和歌山港（春木停車）'},
  '229': {id: 43,  line_id: 2, image_name: '', train_number: '29', train_type: '急行',            kind: 'is_express', section: '難波～極楽橋'},
  '030': {id: 44,  line_id: 0, image_name: '', train_number: '30', train_type: '',                kind: '', section: ''},
  '031': {id: 45,  line_id: 0, image_name: '', train_number: '31', train_type: '',                kind: '', section: ''},
  '232': {id: 46,  line_id: 2, image_name: '', train_number: '32', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～和泉中央'},
  '233': {id: 47,  line_id: 2, image_name: '', train_number: '33', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～河内長野'},
  '234': {id: 48,  line_id: 2, image_name: '', train_number: '34', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～三日市町'},
  '135': {id: 49,  line_id: 1, image_name: '', train_number: '35', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～羽倉崎'},
  '235': {id: 50,  line_id: 2, image_name: '', train_number: '35', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～三日市町～（回送～小原田信号所)'},
  '136': {id: 51,  line_id: 1, image_name: '', train_number: '36', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～樽井'},
  '236': {id: 52,  line_id: 2, image_name: '', train_number: '36', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～林間田園都市'},
  '137': {id: 53,  line_id: 1, image_name: '', train_number: '37', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～みさき公園'},
  '237': {id: 54,  line_id: 2, image_name: '', train_number: '37', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～林間田園都市～（回送小原田信号所）'},
  '138': {id: 55,  line_id: 1, image_name: '', train_number: '38', train_type: '区間急行',        kind: 'is_sectionExpress', section: '難波～和歌山市'},
  '039': {id: 56,  line_id: 0, image_name: '', train_number: '39', train_type: '',                kind: '', section: ''},
  '240': {id: 57,  line_id: 2, image_name: '', train_number: '40', train_type: '準急',            kind: 'is_semiExpress', section: '難波～光明池'},
  '241': {id: 58,  line_id: 2, image_name: '', train_number: '41', train_type: '準急',            kind: 'is_semiExpress', section: '難波～和泉中央'},
  '142': {id: 59,  line_id: 1, image_name: '', train_number: '42', train_type: '準急',            kind: 'is_semiExpress', section: '難波～高石'},
  '242': {id: 60,  line_id: 2, image_name: '', train_number: '42', train_type: '準急',            kind: 'is_semiExpress', section: '難波～和泉中央'},
  '143': {id: 61,  line_id: 1, image_name: '', train_number: '43', train_type: '準急',            kind: 'is_semiExpress', section: '難波～春木'},
  '144': {id: 62,  line_id: 1, image_name: '', train_number: '44', train_type: '準急',            kind: 'is_semiExpress', section: '難波～岸和田～（回送～羽倉崎）'},
  '145': {id: 63,  line_id: 1, image_name: '', train_number: '45', train_type: '準急',            kind: 'is_semiExpress', section: '難波～羽倉崎'},
  '245': {id: 64,  line_id: 2, image_name: '', train_number: '45', train_type: '準急',            kind: 'is_semiExpress', section: '難波～千代田～（回送～千代田信号所）'},
  '146': {id: 65,  line_id: 1, image_name: '', train_number: '46', train_type: '準急',            kind: 'is_semiExpress', section: '難波～樽井'},
  '246': {id: 66,  line_id: 2, image_name: '', train_number: '46', train_type: '準急',            kind: 'is_semiExpress', section: '難波～河内長野'},
  '147': {id: 67,  line_id: 1, image_name: '', train_number: '47', train_type: '準急',            kind: 'is_semiExpress', section: '難波～みさき公園'},
  '247': {id: 68,  line_id: 2, image_name: '', train_number: '47', train_type: '準急',            kind: 'is_semiExpress', section: '難波～三日市町'},
  '048': {id: 69,  line_id: 0, image_name: '', train_number: '48', train_type: '',                kind: '', section: ''},
  '049': {id: 70,  line_id: 0, image_name: '', train_number: '49', train_type: '',                kind: '', section: ''},
  '250': {id: 71,  line_id: 2, image_name: '', train_number: '50', train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '251': {id: 72,  line_id: 2, image_name: '', train_number: '51', train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '152': {id: 73,  line_id: 1, image_name: '', train_number: '52', train_type: '普通',            kind: 'is_local', section: '羽衣～高師浜'},
  '252': {id: 74,  line_id: 2, image_name: '', train_number: '52', train_type: '各停',            kind: 'is_local', section: '難波～光明池'},
  '153': {id: 75,  line_id: 1, image_name: '', train_number: '53', train_type: '普通',            kind: 'is_local', section: '羽衣～高師浜'},
  '253': {id: 76,  line_id: 2, image_name: '', train_number: '53', train_type: '各停',            kind: 'is_local', section: '難波～和泉中央'},
  '154': {id: 77,  line_id: 1, image_name: '', train_number: '54', train_type: '普通',            kind: 'is_local', section: 'みさき公園～多奈川'},
  '254': {id: 78,  line_id: 2, image_name: '', train_number: '54', train_type: '各停',            kind: 'is_local', section: '（堺東～回送）～中百舌鳥～光明池'},
  '155': {id: 79,  line_id: 1, image_name: '', train_number: '55', train_type: '普通',            kind: 'is_local', section: 'みさき公園～多奈川'},
  '255': {id: 80,  line_id: 2, image_name: '', train_number: '55', train_type: '各停',            kind: 'is_local', section: '（堺東～回送）～中百舌鳥～和泉中央'},
  '156': {id: 81,  line_id: 1, image_name: '', train_number: '56', train_type: '普通',            kind: 'is_local', section: '和歌山市～加太'},
  '256': {id: 82,  line_id: 2, image_name: '', train_number: '56', train_type: '各停',            kind: 'is_local', section: '中百舌鳥～光明池'},
  '157': {id: 83,  line_id: 1, image_name: '', train_number: '57', train_type: '普通',            kind: 'is_local', section: '和歌山市～加太'},
  '257': {id: 84,  line_id: 2, image_name: '', train_number: '57', train_type: '各停',            kind: 'is_local', section: '中百舌鳥～和泉中央'},
  '158': {id: 85,  line_id: 1, image_name: '', train_number: '58', train_type: '普通',            kind: 'is_local', section: '和歌山市～和歌山港'},
  '258': {id: 86,  line_id: 2, image_name: '', train_number: '58', train_type: '各停',            kind: 'is_local', section: '中百舌鳥～和泉中央'},
  '059': {id: 87,  line_id: 0, image_name: '', train_number: '59', train_type: '',                kind: '', section: ''},
  '160': {id: 88,  line_id: 1, image_name: '', train_number: '60', train_type: '普通',            kind: 'is_local', section: '難波～住ノ江'},
  '260': {id: 89,  line_id: 2, image_name: '', train_number: '60', train_type: '各停',            kind: 'is_local', section: '難波～堺東'},
  '261': {id: 90,  line_id: 2, image_name: '', train_number: '61', train_type: '各停',            kind: 'is_local', section: '難波～北野田'},
  '162': {id: 91,  line_id: 1, image_name: '', train_number: '62', train_type: '普通',            kind: 'is_local', section: '難波～高石～（回送～羽倉崎）'},
  '262': {id: 92,  line_id: 2, image_name: '', train_number: '62', train_type: '各停',            kind: 'is_local', section: '難波～金剛'},
  '163': {id: 93,  line_id: 1, image_name: '', train_number: '63', train_type: '普通',            kind: 'is_local', section: '難波～春木'},
  '263': {id: 94,  line_id: 2, image_name: '', train_number: '63', train_type: '各停',            kind: 'is_local', section: '難波～千代田～（回送～千代田信号所）'},
  '164': {id: 95,  line_id: 1, image_name: '', train_number: '64', train_type: '普通',            kind: 'is_local', section: '難波～泉佐野'},
  '264': {id: 96,  line_id: 2, image_name: '', train_number: '64', train_type: '各停',            kind: 'is_local', section: '難波～河内長野'},
  '165': {id: 97,  line_id: 1, image_name: '', train_number: '65', train_type: '普通',            kind: 'is_local', section: '難波～羽倉崎'},
  '265': {id: 98,  line_id: 2, image_name: '', train_number: '65', train_type: '各停',            kind: 'is_local', section: '難波～河内長野'},
  '166': {id: 99,  line_id: 1, image_name: '', train_number: '66', train_type: '普通',            kind: 'is_local', section: '難波～樽井'},
  '266': {id: 100, line_id: 2, image_name: '', train_number: '66', train_type: '各停',            kind: 'is_local', section: '難波～三日市町'},
  '167': {id: 101, line_id: 1, image_name: '', train_number: '67', train_type: '普通',            kind: 'is_local', section: '難波～みさき公園'},
  '267': {id: 102, line_id: 2, image_name: '', train_number: '67', train_type: '各停',            kind: 'is_local', section: '難波～林間田園都市～（回送～小原田信号所）'},
  '168': {id: 103, line_id: 1, image_name: '', train_number: '68', train_type: '普通',            kind: 'is_local', section: '難波～和歌山市'},
  '169': {id: 104, line_id: 1, image_name: '', train_number: '69', train_type: '普通',            kind: 'is_local', section: '難波～和歌山市'},
  '269': {id: 105, line_id: 2, image_name: '', train_number: '69', train_type: '各停',            kind: 'is_local', section: '難波～橋本'},
  '170': {id: 106, line_id: 1, image_name: 'train_airport_normal', train_number: '70', train_type: '普通',            kind: 'is_local', section: '難波・住ノ江～関西空港'},
  '270': {id: 107, line_id: 2, image_name: '', train_number: '70', train_type: '各停',            kind: 'is_local', section: '（千代田信号所～回送）～橋本～高野下～（回送～極楽橋）'},
  '171': {id: 108, line_id: 1, image_name: 'train_airport_normal', train_number: '71', train_type: '普通',            kind: 'is_local', section: '泉佐野～関西空港'},
  '271': {id: 109, line_id: 2, image_name: '', train_number: '71', train_type: '各停',            kind: 'is_local', section: '（千代田信号所～回送）～河内長野～極楽橋'},
  '172': {id: 110, line_id: 1, image_name: 'train_airport_normal', train_number: '72', train_type: '普通',            kind: 'is_local', section: '（貝塚～回送）～泉佐野～関西空港'},
  '272': {id: 111, line_id: 2, image_name: '', train_number: '72', train_type: '各停',            kind: 'is_local', section: '（小原田信号所～回送）～橋本～高野下'},
  '273': {id: 112, line_id: 2, image_name: '', train_number: '73', train_type: '各停',            kind: 'is_local', section: '（小原田信号所～回送）～橋本～極楽橋'},
  '174': {id: 113, line_id: 1, image_name: '', train_number: '74', train_type: '普通',            kind: 'is_local', section: '住ノ江～泉佐野'},
  '274': {id: 114, line_id: 2, image_name: '', train_number: '74', train_type: '各停',            kind: 'is_local', section: '橋本～高野下'},
  '175': {id: 115, line_id: 1, image_name: '', train_number: '75', train_type: '普通',            kind: 'is_local', section: '住ノ江～羽倉崎'},
  '275': {id: 116, line_id: 2, image_name: '', train_number: '75', train_type: '各停',            kind: 'is_local', section: '橋本～極楽橋'},
  '176': {id: 117, line_id: 1, image_name: '', train_number: '76', train_type: '普通',            kind: 'is_local', section: '泉大津～羽倉崎'},
  '276': {id: 118, line_id: 2, image_name: '', train_number: '76', train_type: '各停',            kind: 'is_local', section: '（千代田信号所～回送）～河内長野～橋本'},
  '077': {id: 119, line_id: 0, image_name: '', train_number: '77', train_type: '',                kind: '', section: ''},
  '178': {id: 120, line_id: 1, image_name: '', train_number: '78', train_type: '普通',            kind: 'is_local', section: '泉佐野～和歌山市'},
  '278': {id: 121, line_id: 2, image_name: '', train_number: '78', train_type: '鋼索線',          kind: '', section: '極楽橋～高野山'},
  '179': {id: 122, line_id: 1, image_name: '', train_number: '79', train_type: '普通',            kind: 'is_local', section: '羽倉崎～和歌山市'},
  '279': {id: 123, line_id: 2, image_name: '', train_number: '79', train_type: '鋼索線',          kind: '', section: '極楽橋～高野山'},
  '180': {id: 124, line_id: 1, image_name: '', train_number: '80', train_type: '回送',            kind: '', section: '難波・岸里玉出～住ノ江・岸里玉出'},
  '280': {id: 125, line_id: 2, image_name: '', train_number: '80', train_type: '回送',            kind: '', section: '難波→光明池 / 和泉中央→中百舌鳥・堺東'},
  '181': {id: 126, line_id: 1, image_name: '', train_number: '81', train_type: '回送',            kind: '', section: '難波～高石'},
  '281': {id: 127, line_id: 2, image_name: '', train_number: '81', train_type: '回送',            kind: '', section: '難波→和泉中央 / 和泉中央→難波'},
  '182': {id: 128, line_id: 1, image_name: '', train_number: '82', train_type: '回送',            kind: '', section: '住ノ江・羽衣～高石・高師浜・羽衣'},
  '282': {id: 129, line_id: 2, image_name: '', train_number: '82', train_type: '回送',            kind: '', section: '光明池→和泉中央 / 和泉中央→光明池'},
  '183': {id: 130, line_id: 1, image_name: '', train_number: '83', train_type: '回送',            kind: '', section: '難波・住ノ江・羽衣～春木・泉大津'},
  '283': {id: 131, line_id: 2, image_name: '', train_number: '83', train_type: '回送',            kind: '', section: '難波→堺東 / 極楽橋→堺東'},
  '184': {id: 132, line_id: 1, image_name: '', train_number: '84', train_type: '回送',            kind: '', section: '難波・住ノ江～羽倉崎・泉佐野・樽井・みさき公園'},
  '284': {id: 133, line_id: 2, image_name: '', train_number: '84', train_type: '回送',            kind: '', section: '難波→北野田'},
  '185': {id: 134, line_id: 1, image_name: '', train_number: '85', train_type: '回送',            kind: '', section: '貝塚・泉佐野～泉佐野・羽倉崎・樽井・尾崎・みさき公園'},
  '285': {id: 135, line_id: 2, image_name: '', train_number: '85', train_type: '回送',            kind: '', section: '難波→金剛'},
  '186': {id: 136, line_id: 1, image_name: '', train_number: '86', train_type: '回送',            kind: '', section: '羽倉崎～みさき公園・樽井・尾崎'},
  '286': {id: 137, line_id: 2, image_name: '', train_number: '86', train_type: '回送',            kind: '', section: '難波→千代田信号所 / 極楽橋→千代田信号所'},
  '187': {id: 138, line_id: 1, image_name: '', train_number: '87', train_type: '回送',            kind: '', section: '羽倉崎・みさき公園・泉佐野～和歌山市・和歌山港'},
  '287': {id: 139, line_id: 2, image_name: '', train_number: '87', train_type: '回送',            kind: '', section: '難波→河内長野'},
  '188': {id: 140, line_id: 1, image_name: '', train_number: '88', train_type: '回送',            kind: '', section: '難波・住ノ江～和歌山市'},
  '288': {id: 141, line_id: 2, image_name: '', train_number: '88', train_type: '回送',            kind: '', section: '難波→三日市町'},
  '189': {id: 142, line_id: 1, image_name: '', train_number: '89', train_type: '回送',            kind: '', section: '和歌山市～和歌山港'},
  '289': {id: 143, line_id: 2, image_name: '', train_number: '89', train_type: '回送',            kind: '', section: '難波→林間田園都市'},
  '290': {id: 144, line_id: 2, image_name: '', train_number: '90', train_type: '回送',            kind: '', section: '汐見橋→岸里玉出 / 岸里玉出→汐見橋'},
  '191': {id: 145, line_id: 1, image_name: '', train_number: '91', train_type: '回送',            kind: '', section: '難波～関西空港'},
  '291': {id: 146, line_id: 2, image_name: '', train_number: '91', train_type: '回送',            kind: '', section: '難波→小原田信号所 / 極楽橋→小原田信号所'},
  '192': {id: 147, line_id: 1, image_name: '', train_number: '92', train_type: '回送',            kind: '', section: '住ノ江～関西空港'},
  '292': {id: 148, line_id: 2, image_name: '', train_number: '92', train_type: '回送',            kind: '', section: '難波→橋本 / 極楽橋→橋本'},
  '193': {id: 149, line_id: 1, image_name: '', train_number: '93', train_type: '回送',            kind: '', section: '貝塚・泉佐野～関西空港'},
  '293': {id: 150, line_id: 2, image_name: '', train_number: '93', train_type: '回送',            kind: '', section: '難波→高野下'},
  '294': {id: 151, line_id: 2, image_name: '', train_number: '94', train_type: '回送',            kind: '', section: '難波→極楽橋 / 極楽橋→難波'},
  '095': {id: 152, line_id: 0, image_name: '', train_number: '95', train_type: '',                kind: '', section: ''},
  '196': {id: 153, line_id: 1, image_name: '', train_number: '96', train_type: '回送',            kind: '', section: 'みさき公園～多奈川'},
  '296': {id: 154, line_id: 2, image_name: '', train_number: '96', train_type: '回送',            kind: '', section: '極楽橋→中百舌鳥'},
  '197': {id: 155, line_id: 1, image_name: '', train_number: '97', train_type: '回送',            kind: '', section: '和歌山市～加太'},
  '297': {id: 156, line_id: 2, image_name: '', train_number: '97', train_type: '高野線',          kind: '', section: '団体専用（泉北直通）'},
  '198': {id: 157, line_id: 1, image_name: '', train_number: '98', train_type: '南海線',          kind: '', section: '団体専用（回送含む）'},
  '298': {id: 158, line_id: 2, image_name: '', train_number: '98', train_type: '高野線',          kind: '', section: '団体専用'},
  '099': {id: 159, line_id: 0, image_name: '', train_number: '99', train_type: '',                kind: '', section: ''},

}

export const NANKAI_TRAIN_KINDS = {
  '0': {id: 0, image_name: '',              train_type: '',        kind: '', section: ''},
  '1': {id: 1, image_name: 'train_rapit_a',    train_type: 'ﾗﾋﾟｰﾄα',   kind: 'is_rapit', section: '難波～関西空港（ノンストップ）'},
  '2': {id: 2, image_name: 'train_rapit_a',    train_type: 'ﾗﾋﾟｰﾄα',  kind: 'is_rapit', section: '難波～関西空港（ノンストップ）'},
  '3': {id: 3, image_name: 'train_rapit_b',    train_type: 'ﾗﾋﾟｰﾄβ',   kind: 'is_rapit', section: '橋本～極楽橋'},
  '4': {id: 4, image_name: 'train_sazan',      train_type: 'サザン',      kind: 'is_sazan', section: '難波～関西空港'},
  '5': {id: 5, image_name: 'train_sazan',      train_type: 'サザン',      kind: 'is_sazan', section: '難波～和泉中央'},
  '6': {id: 6, image_name: 'train_sazan',      train_type: '特急',      kind: 'is_sazan', section: '難波～和歌山市（全席指定）'},
  '7': {id: 7, image_name: 'train_express',   train_type: '急行',        kind: 'is_express', section: '難波～和歌山市'},
  '8': {id: 8, image_name: 'train_express',   train_type: '急行',        kind: 'is_express', section: '難波～和歌山市'},
  '9': {id: 9, image_name: 'train_express',   train_type: '急行',        kind: 'is_express', section: '難波・和歌山市～和歌山港'},
  '10': {id: 10, image_name: 'train_express',  train_type: '急行',        kind: 'is_express', section: '難波～極楽橋'},
  '11': {id: 11, image_name: 'train_airport_express',  train_type: '空港急行',        kind: 'is_express', section: '難波～関西空港'},
  '12': {id: 12, image_name: 'train_airport_express',  train_type: '空港急行',        kind: 'is_express', section: '難波～関西空港'},
  '13': {id: 13, image_name: 'train_section_express',   train_type: '区急',     kind: 'is_sectionExpress', section: '難波～和泉中央'},
  '14': {id: 14, image_name: 'train_section_express',   train_type: '区急',     kind: 'is_sectionExpress', section: '難波～河内長野'},
  '15': {id: 15, image_name: 'train_semi_express',    train_type: '準急',        kind: 'is_semiExpress', section: '難波～光明池'},
  '16': {id: 16, image_name: 'train_semi_express',    train_type: '準急',        kind: 'is_semiExpress', section: '難波～和泉中央'},
  '17': {id: 17, image_name: 'train_semi_express',    train_type: '準急',        kind: 'is_semiExpress', section: '難波～高石'},
  '18': {id: 18, image_name: 'train_normal',    train_type: '普通',        kind: 'is_local', section: '羽衣～高師浜'},
  '19': {id: 19, image_name: 'train_normal',    train_type: '普通',        kind: 'is_local', section: '難波～住ノ江'},
  '20': {id: 20, image_name: 'train_airport_normal',    train_type: '普通',        kind: 'is_local', section: '難波～関西空港'},
  '21': {id: 21, image_name: 'train_airport_normal',    train_type: '普通',        kind: 'is_local', section: '難波～関西空港'},
  '22': {id: 22, image_name: 'train_airport_normal',    train_type: '普通',        kind: 'is_local', section: '貝塚～関西空港（貝塚～泉佐野間回送）'},
  '23': {id: 23, image_name: 'train_normal',    train_type: '普通',        kind: 'is_local', section: '難波～羽倉崎'},
  '24': {id: 24, image_name: '',              train_type: '回送',        kind: '', section: '難波→河内長野'},
  '25': {id: 25, image_name: '',              train_type: '回送',        kind: '', section: '難波・住ノ江～和歌山市'},
  '26': {id: 26, image_name: '',              train_type: '回送',        kind: '', section: '難波→三日市町'},
  '27': {id: 27, image_name: 'train_normal',              train_type: '普通',        kind: 'is_local', section: '難波～和歌山市'},
  '28': {id: 28, image_name: 'train_normal',              train_type: '普通',        kind: 'is_local', section: '難波～和歌山市'},
  '29': {id: 29, image_name: 'train_normal',              train_type: '普通',        kind: 'is_local', section: '難波～住ノ江 羽衣～高師浜 みさき公園～多奈川 汐見橋～岸里玉出 加太〜東松江'},
  '30': {id: 30, image_name: '',              train_type: '回送',        kind: '', section: '難波～関西空港'},
  '31': {id: 31, image_name: '',              train_type: '回送',        kind: '', section: '難波→小原田信号所 / 極楽橋→小原田信号所'},
  '32': {id: 32, image_name: '',              train_type: '回送',        kind: '', section: '住ノ江～関西空港'},
}

export const KOYA_TRAIN_KINDS = {
  '0': {id: 0, image_name: '',               train_type: '',               kind: '', section: ''},
  '1': {id: 1, image_name: 'train_koya',       train_type: 'GRAN 天空', kind: 'is_gran_tenkuu', section: '難波〜極楽橋'},
  '2': {id: 2, image_name: 'train_koya',       train_type: 'こうや',         kind: 'is_koya', section: '橋本～極楽橋'},
  '3': {id: 3, image_name: 'train_rinkan',       train_type: 'りんかん',        kind: 'is_rinkan', section: '難波～関西空港'},
  '4': {id: 4, image_name: 'train_tenku', train_type: '天空',        kind: 'is_tenku', section: '難波～和泉中央'},
  '5': {id: 5, image_name: 'train_senboku',     train_type: '泉北ﾗｲﾅｰ',     kind: 'is_senboku', section: '難波～和歌山市（全席指定）'},
  '6': {id: 6, image_name: 'train_koya',       train_type: '特急',           kind: 'is_koya', section: '難波～和歌山港（全席指定）'},
  '7': {id: 7, image_name: '',               train_type: '',               kind: '', section: ''},
  '8': {id: 8, image_name: 'train_rapid',   train_type: '快急',        kind: 'is_rapid', section: '難波～橋本'},
  '9': {id: 9, image_name: '',               train_type: '',               kind: '', section: ''},
  '10': {id: 10, image_name: '',               train_type: '',               kind: '', section: ''},
  '11': {id: 11, image_name: 'train_express',   train_type: '急行',            kind: 'is_express', section: '難波～三日市町'},
  '12': {id: 12, image_name: 'train_express',   train_type: '急行',            kind: 'is_express', section: '難波～林間田園都市'},
  '13': {id: 13, image_name: 'train_express',   train_type: '急行',            kind: 'is_express', section: '難波～みさき公園～（回送～和歌山市）'},
  '14': {id: 14, image_name: 'train_express',   train_type: '急行',            kind: 'is_express', section: '難波～林間田園都市～（回送～小原田信号所）'},
  '15': {id: 15, image_name: '',               train_type: '',                kind: '', section: ''},
  '16': {id: 16, image_name: '',               train_type: '',                kind: '', section: ''},
  '17': {id: 17, image_name: '',               train_type: '',                kind: '', section: ''},
  '18': {id: 18, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '難波～羽倉崎'},
  '19': {id: 19, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '難波～羽倉崎'},
  '20': {id: 20, image_name: '',               train_type: '',                kind: '', section: ''},
  '21': {id: 21, image_name: '',               train_type: '',                kind: '', section: ''},
  '22': {id: 22, image_name: '',               train_type: '',                kind: '', section: ''},
  '23': {id: 23, image_name: '',               train_type: '',                kind: '', section: ''},
  '24': {id: 24, image_name: '',              train_type: '回送',            kind: '', section: '難波・岸里玉出～住ノ江・岸里玉出'},
  '25': {id: 25, image_name: '',              train_type: '回送',            kind: '', section: '難波・岸里玉出～住ノ江・岸里玉出'},
  '26': {id: 26, image_name: '',              train_type: '回送',            kind: '', section: '難波・岸里玉出～住ノ江・岸里玉出'},
  '27': {id: 27, image_name: '',               train_type: '',                kind: '', section: ''},
  '28': {id: 28, image_name: '',               train_type: '',                kind: '', section: ''},
  '29': {id: 29, image_name: '',               train_type: '',                kind: '', section: ''},
  '30': {id: 30, image_name: '',               train_type: '',            kind: '', section: '難波～光明池'},
  '31': {id: 31, image_name: 'train_semi_express',     train_type: '準急',            kind: 'is_semiExpress', section: '難波～光明池'},
  '32': {id: 32, image_name: 'train_semi_express',     train_type: '準急',            kind: 'is_semiExpress', section: '難波～光明池'},
  '33': {id: 33, image_name: 'train_semi_express',     train_type: '準急',            kind: 'is_semiExpress', section: '難波～光明池'},
  '34': {id: 34, image_name: 'train_semi_express',     train_type: '準急',            kind: 'is_semiExpress', section: ''},
  '35': {id: 35, image_name: '',               train_type: '',                kind: '', section: ''},
  '36': {id: 36, image_name: '',               train_type: '',                kind: '', section: ''},
  '37': {id: 37, image_name: '',               train_type: '',                kind: '', section: ''},
  '38': {id: 38, image_name: '',               train_type: '',                kind: '', section: ''},
  '39': {id: 39, image_name: '',               train_type: '',                kind: '', section: ''},
  '40': {id: 40, image_name: '',               train_type: '',               kind: '', section: '難波～和泉中央'},
  '41': {id: 41, image_name: 'train_section_express',    train_type: '区急',        kind: 'is_sectionExpress', section: '難波～河内長野'},
  '42': {id: 42, image_name: 'train_section_express',    train_type: '区急',        kind: 'is_sectionExpress', section: '難波～三日市町'},
  '43': {id: 43, image_name: 'train_section_express',    train_type: '区急',        kind: 'is_sectionExpress', section: '難波～羽倉崎'},
  '44': {id: 44, image_name: 'train_section_express',    train_type: '区急',        kind: 'is_sectionExpress', section: '難波～三日市町～（回送～小原田信号所)'},
  '45': {id: 45, image_name: 'train_section_express',    train_type: '区急',        kind: 'is_sectionExpress', section: '難波～樽井'},
  '46': {id: 46, image_name: 'train_section_express',    train_type: '区急',        kind: 'is_sectionExpress', section: ''},
  '47': {id: 47, image_name: '',               train_type: '',                kind: '', section: ''},
  '48': {id: 48, image_name: '',               train_type: '',                kind: '', section: ''},
  '49': {id: 49, image_name: '',               train_type: '',                kind: '', section: ''},
  '50': {id: 50, image_name: '',               train_type: '',                kind: '', section: ''},
  '51': {id: 51, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '52': {id: 52, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '53': {id: 53, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '54': {id: 54, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '55': {id: 55, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '56': {id: 56, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '57': {id: 57, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '58': {id: 58, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '59': {id: 59, image_name: 'train_local',     train_type: '各停',            kind: 'is_local', section: '汐見橋～岸里玉出'},
  '60': {id: 60, image_name: '',               train_type: '',                kind: '', section: ''},
  '61': {id: 61, image_name: '',               train_type: '',                kind: '', section: ''},
  '62': {id: 62, image_name: '',               train_type: '',                kind: '', section: ''},
  '63': {id: 63, image_name: '',               train_type: '',                kind: '', section: ''},
  '64': {id: 64, image_name: '',               train_type: '',                kind: '', section: ''},
  '65': {id: 65, image_name: '',               train_type: '',                kind: '', section: ''},
  '66': {id: 66, image_name: '',               train_type: '',                kind: '', section: ''},
  '67': {id: 67, image_name: '',               train_type: '',                kind: '', section: ''},
  '68': {id: 68, image_name: '',               train_type: '',                kind: '', section: ''},
  '69': {id: 69, image_name: '',               train_type: '',                kind: '', section: ''},
  '70': {id: 70, image_name: '',               train_type: '',                kind: '', section: ''},
  '71': {id: 71, image_name: '',               train_type: '鋼索線',          kind: '', section: '極楽橋～高野山'},
  '72': {id: 72, image_name: '',               train_type: '',                kind: '', section: ''},
  '73': {id: 73, image_name: '',               train_type: '',                kind: '', section: ''},
  '74': {id: 74, image_name: '',               train_type: '',                kind: '', section: ''},
  '75': {id: 75, image_name: '',               train_type: '',                kind: '', section: ''},
  '76': {id: 76, image_name: '',               train_type: '',                kind: '', section: ''},
  '77': {id: 77, image_name: '',               train_type: '',                kind: '', section: ''},
  '78': {id: 78, image_name: '',               train_type: '',                kind: '', section: ''},
  '79': {id: 79, image_name: '',               train_type: '',                kind: '', section: ''},
  '80': {id: 80, image_name: '',               train_type: '',                kind: '', section: ''},
  '81': {id: 81, image_name: '',              train_type: '鋼索線',          kind: '', section: '極楽橋～高野山'},
  '82': {id: 82, image_name: '',              train_type: '鋼索線',          kind: '', section: '極楽橋～高野山'},
  '83': {id: 83, image_name: '',               train_type: '',                kind: '', section: ''},
  '84': {id: 84, image_name: '',               train_type: '',                kind: '', section: ''},
  '85': {id: 85, image_name: '',               train_type: '',                kind: '', section: ''},
  '86': {id: 86, image_name: '',               train_type: '',                kind: '', section: ''},
  '87': {id: 87, image_name: '',               train_type: '',                kind: '', section: ''},
  '88': {id: 88, image_name: '',               train_type: '',                kind: '', section: ''},
  '89': {id: 89, image_name: '',               train_type: '',                kind: '', section: ''},
  '90': {id: 90, image_name: '',               train_type: '',                kind: '', section: ''},
  '91': {id: 91, image_name: '',               train_type: '',                kind: '', section: ''},
  '92': {id: 92, image_name: '',               train_type: '',                kind: '', section: ''},
  '93': {id: 93, image_name: '',               train_type: '',                kind: '', section: ''},
  '94': {id: 94, image_name: '',               train_type: '',                kind: '', section: ''},
  '95': {id: 95, image_name: '',               train_type: '',                kind: '', section: ''},
  '96': {id: 96, image_name: '',               train_type: '',                kind: '', section: ''},
  '97': {id: 97, image_name: '',               train_type: '',                kind: '', section: ''},
  '98': {id: 98, image_name: '',               train_type: '',                kind: '', section: ''},
  '99': {id: 99, image_name: '',               train_type: '',                kind: '', section: ''},
}

export const NANKAI_DESTINATION_STATIONS = {
  '1': {id: 1, destination_name: 'なんば'},
  '2': {id: 2, destination_name: ''},
  '3': {id: 3, destination_name: '新今宮'},
  '4': {id: 4, destination_name: ''},
  '5': {id: 5, destination_name: '天下茶屋'},
  '6': {id: 6, destination_name: '岸里玉出'},
  '7': {id: 7, destination_name: '粉浜'},
  '8': {id: 8, destination_name: '住吉大社'},
  '9': {id: 9, destination_name: '住之江'},
  '10': {id: 10, destination_name: '七道'},
  '11': {id: 11, destination_name: '堺'},
  '12': {id: 12, destination_name: '湊'},
  '13': {id: 13, destination_name: '石津川'},
  '14': {id: 14, destination_name: '諏訪ノ森'},
  '15': {id: 15, destination_name: '浜寺公園'},
  '16': {id: 16, destination_name: '羽衣'},
  '17': {id: 17, destination_name: '高石'},
  '18': {id: 18, destination_name: '北助松'},
  '19': {id: 19, destination_name: '松ノ浜'},
  '20': {id: 20, destination_name: '泉大津'},
  '21': {id: 21, destination_name: '忠岡'},
  '22': {id: 22, destination_name: '春木'},
  '23': {id: 23, destination_name: '和泉大宮'},
  '24': {id: 24, destination_name: '岸和田'},
  '25': {id: 25, destination_name: '蛸地蔵'},
  '26': {id: 26, destination_name: '貝塚'},
  '27': {id: 27, destination_name: '二色浜'},
  '28': {id: 28, destination_name: '鶴原'},
  '29': {id: 29, destination_name: '井原里'},
  '30': {id: 30, destination_name: '泉佐野'},
  '31': {id: 31, destination_name: '羽倉崎'},
  '32': {id: 32, destination_name: '吉見ノ里'},
  '33': {id: 33, destination_name: '岡田浦'},
  '34': {id: 34, destination_name: '樽井'},
  '35': {id: 35, destination_name: '尾崎'},
  '36': {id: 36, destination_name: '鳥取ノ荘'},
  '37': {id: 37, destination_name: '箱作'},
  '38': {id: 38, destination_name: '淡輪'},
  '39': {id: 39, destination_name: 'みさき公園'},
  '40': {id: 40, destination_name: '孝子'},
  '41': {id: 41, destination_name: '和歌山大学前'},
  '42': {id: 42, destination_name: '紀ノ川'},
  '43': {id: 43, destination_name: '和歌山市'},
  '44': {id: 44, destination_name: ''},
  '45': {id: 45, destination_name: ''},
  '46': {id: 46, destination_name: '和歌山港'},
  '47': {id: 47, destination_name: ''},
  '48': {id: 48, destination_name: ''},
  '49': {id: 49, destination_name: 'りんくうタウン'},
  '50': {id: 50, destination_name: '関西空港'},
  '51': {id: 51, destination_name: ''},
  '52': {id: 52, destination_name: ''},
  '53': {id: 53, destination_name: '梶取'},
  '54': {id: 54, destination_name: '東松江'},
  '55': {id: 55, destination_name: '中松江'},
  '56': {id: 56, destination_name: '八幡前'},
  '57': {id: 57, destination_name: '西ノ庄'},
  '58': {id: 58, destination_name: '二里ヶ浜'},
  '59': {id: 59, destination_name: '磯ノ浦'},
  '60': {id: 60, destination_name: '加太'},
  '61': {id: 61, destination_name: ''},
  '62': {id: 62, destination_name: ''},
  '63': {id: 63, destination_name: '深日町'},
  '64': {id: 64, destination_name: '深日港'},
  '65': {id: 65, destination_name: '多奈川'},
  '66': {id: 66, destination_name: ''},
  '67': {id: 67, destination_name: ''},
  '68': {id: 68, destination_name: '伽羅橋'},
  '69': {id: 69, destination_name: '高師浜'},
  '70': {id: 70, destination_name: ''},
  '71': {id: 71, destination_name: ''},
  '72': {id: 72, destination_name: '汐見橋'},
  '73': {id: 73, destination_name: '芦原町'},
  '74': {id: 74, destination_name: '木津川'},
  '75': {id: 75, destination_name: '津守'},
  '76': {id: 76, destination_name: '西天下茶屋'},
  '77': {id: 77, destination_name: ''},
  '78': {id: 78, destination_name: ''},
  '79': {id: 79, destination_name: ''},
  '80': {id: 80, destination_name: '―'},
}

export const KOYA_DESTINATION_STATIONS = {
  '1': {id: 1, destination_name: 'なんば'},
  '2': {id: 2, destination_name: '今宮戎'},
  '3': {id: 3, destination_name: '新今宮'},
  '4': {id: 4, destination_name: '萩ノ茶屋'},
  '5': {id: 5, destination_name: '天下茶屋'},
  '6': {id: 6, destination_name: '岸里玉出'},
  '7': {id: 7, destination_name: '帝塚山'},
  '8': {id: 8, destination_name: '住吉東'},
  '9': {id: 9, destination_name: '沢ノ町'},
  '10': {id: 10, destination_name: '我孫子前'},
  '11': {id: 11, destination_name: '浅香山'},
  '12': {id: 12, destination_name: '堺東'},
  '13': {id: 13, destination_name: '三国ヶ丘'},
  '14': {id: 14, destination_name: '百舌鳥八幡'},
  '15': {id: 15, destination_name: '中百舌鳥'},
  '16': {id: 16, destination_name: '白鷺'},
  '17': {id: 17, destination_name: '初芝'},
  '18': {id: 18, destination_name: '萩原天神'},
  '19': {id: 19, destination_name: '北野田'},
  '20': {id: 20, destination_name: '狭山'},
  '21': {id: 21, destination_name: '大阪狭山市'},
  '22': {id: 22, destination_name: '金剛'},
  '23': {id: 23, destination_name: '滝谷'},
  '24': {id: 24, destination_name: '千代田'},
  '25': {id: 25, destination_name: '千代田信号場'},
  '26': {id: 26, destination_name: '河内長野'},
  '27': {id: 27, destination_name: '三日市町'},
  '28': {id: 28, destination_name: '美加の台'},
  '29': {id: 29, destination_name: '千早口'},
  '30': {id: 30, destination_name: '天見'},
  '31': {id: 31, destination_name: '紀見峠'},
  '32': {id: 32, destination_name: '林間田園都市'},
  '33': {id: 33, destination_name: '御幸辻'},
  '34': {id: 34, destination_name: '小原田信号場'},
  '35': {id: 35, destination_name: '橋本'},
  '36': {id: 36, destination_name: '紀伊清水'},
  '37': {id: 37, destination_name: '学文路'},
  '38': {id: 38, destination_name: '九度山'},
  '39': {id: 39, destination_name: '高野下'},
  '40': {id: 40, destination_name: '下古沢'},
  '41': {id: 41, destination_name: '上古沢'},
  '42': {id: 42, destination_name: '紀伊細川'},
  '43': {id: 43, destination_name: '紀伊神谷'},
  '44': {id: 44, destination_name: '極楽橋'},
  '45': {id: 45, destination_name: ''},
  '46': {id: 46, destination_name: ''},
  '47': {id: 47, destination_name: ''},
  '48': {id: 48, destination_name: ''},
  '49': {id: 49, destination_name: ''},
  '50': {id: 50, destination_name: ''},
  '51': {id: 51, destination_name: ''},
  '52': {id: 52, destination_name: '高野山'},
  '53': {id: 53, destination_name: ''},
  '54': {id: 54, destination_name: ''},
  '55': {id: 55, destination_name: ''},
  '56': {id: 56, destination_name: ''},
  '57': {id: 57, destination_name: ''},
  '58': {id: 58, destination_name: ''},
  '59': {id: 59, destination_name: ''},
  '60': {id: 60, destination_name: ''},
  '61': {id: 61, destination_name: ''},
  '62': {id: 62, destination_name: '深井'},
  '63': {id: 63, destination_name: '泉ケ丘'},
  '64': {id: 64, destination_name: '栂・美木多'},
  '65': {id: 65, destination_name: '光明池'},
  '66': {id: 66, destination_name: '和泉中央'},
  '67': {id: 67, destination_name: ''},
  '68': {id: 68, destination_name: ''},
  '69': {id: 69, destination_name: ''},
  '70': {id: 70, destination_name: ''},
  '71': {id: 71, destination_name: ''},
  '72': {id: 72, destination_name: '汐見橋'},
  '73': {id: 73, destination_name: '芦原町'},
  '74': {id: 74, destination_name: '木津川'},
  '75': {id: 75, destination_name: '津守'},
  '76': {id: 76, destination_name: '西天下茶屋'},
  '77': {id: 77, destination_name: ''},
  '78': {id: 78, destination_name: ''},
  '79': {id: 79, destination_name: ''},
  '80': {id: 80, destination_name: '―'},
}

export const SPECIAL_TRAIN_CARS = {
  '1': {car_number: 7167, image_name: 'train_kai',},
  '2': {car_number: 7962, image_name: 'train_kai',},
  '3': {car_number: 7187, image_name: 'train_sachi',},
  '4': {car_number: 7967, image_name: 'train_sachi',},
  '5': {car_number: 7197, image_name: 'train_nana',},
  '6': {car_number: 7970, image_name: 'train_nana',},
  '7': {car_number: 12001, image_name: 'train_southern_premium',},
  '8': {car_number: 12801, image_name: 'train_southern_premium',},
  '9': {car_number: 12851, image_name: 'train_southern_premium',},
  '10': {car_number: 12101, image_name: 'train_southern_premium',},
  '11': {car_number: 12002, image_name: 'train_southern_premium',},
  '12': {car_number: 12802, image_name: 'train_southern_premium',},
  '13': {car_number: 12852, image_name: 'train_southern_premium',},
  '14': {car_number: 12102, image_name: 'train_southern_premium',},
}

export const KASHIRA_TRAIN_CARS = {
  '1': {car_number: 7195, image_name: 'train_kashira',},
  '2': {car_number: 7969, image_name: 'train_kashira',},
}

// 他社アプリ連携リンク
export const OTHER_APP_LINKS = [
  { station_id: 1, transfer: '阪神線（大阪難波駅）', link: 'nankaiapp://out/?company=hanshin&lid=2&sid=121', image_name: 'norikae_btn_hanshin' },
  { station_id: 1, transfer: '近鉄線（大阪難波駅）', link: 'nankaiapp://out/?company=kintetsu&lid=003', image_name: 'norikae_btn_kintetsu' },
  { station_id: 1, transfer: 'JR線 大和路線（JR難波駅）', link: 'nankaiapp://out/?company=westjr&lid=1620&sid=699', image_name: 'norikae_btn_wester' },
  { station_id: 2, transfer: 'JR線 大和路線（新今宮駅） 大阪環状線（新今宮駅）', link: ['nankaiapp://out/?company=westjr&lid=1621&sid=696', 'nankaiapp://out/?company=westjr&lid=7191&sid=696'], image_name: 'norikae_btn_wester' },
  { station_id: 14, transfer: 'JR線 阪和線（東羽衣駅）', link: 'nankaiapp://out/?company=westjr&lid=1730&sid=731', image_name: 'norikae_btn_wester' },
  { station_id: 76, transfer: 'JR線 関西空港線（りんくうタウン駅）', link: 'nankaiapp://out/?company=westjr&lid=1711&sid=747', image_name: 'norikae_btn_wester' },
  { station_id: 77, transfer: 'JR線 関西空港線（関西空港駅）', link: 'nankaiapp://out/?company=westjr&lid=1710&sid=679', image_name: 'norikae_btn_wester' },
  { station_id: 95, transfer: '阪神線（大阪難波駅）', link: 'nankaiapp://out/?company=hanshin&lid=2&sid=121', image_name: 'norikae_btn_hanshin' },
  { station_id: 95, transfer: '近鉄線（大阪難波駅）', link: 'nankaiapp://out/?company=kintetsu&lid=003', image_name: 'norikae_btn_kintetsu' },
  { station_id: 95, transfer: 'JR線 大和路線（JR難波駅）', link: 'nankaiapp://out/?company=westjr&lid=1620&sid=699', image_name: 'norikae_btn_wester' },
  { station_id: 97, transfer: 'JR線 大和路線（新今宮駅） 大阪環状線（新今宮駅）', link: ['nankaiapp://out/?company=westjr&lid=1621&sid=696', 'nankaiapp://out/?company=westjr&lid=7191&sid=696'], image_name: 'norikae_btn_wester' },
  { station_id: 107, transfer: 'JR線 阪和線（三国ヶ丘駅）', link: 'nankaiapp://out/?company=westjr&lid=1721&sid=740', image_name: 'norikae_btn_wester' },
  { station_id: 127, transfer: 'JR線 和歌山線（橋本駅）', link: 'nankaiapp://out/?company=westjr&lid=1701&sid=978', image_name: 'norikae_btn_wester' },
  { station_id: 137, transfer: '阪神線（桜川駅）', link: 'nankaiapp://out/?company=hanshin&lid=2&sid=49', image_name: 'norikae_btn_hanshin' },
  { station_id: 119, transfer: '近鉄線（河内長野駅）', link: 'nankaiapp://out/?company=kintetsu&lid=014', image_name: 'norikae_btn_kintetsu' },
]

// toiletType:Vacan API のattachmentGroupList>toiletTypeで定義されている内容
export const RESTROOM_STALL_TYPE = {
  '1': {toiletType: 'male', icon_name: 'men'},
  '2': {toiletType: 'female', icon_name: 'women'},
  '3': {toiletType: 'accessible', icon_name: 'tamokuteki'},
}
export const RESTROOM_STATION_FACILITIES = {
  '1': {facility_ids:[1]},
  '95': {facility_ids:[1]},
}
// opening_houresは00:00からの秒数を指定する。
// opening_houres_endが24時を超える場合は24時以上で定義する。
// noteは開発様メモでアプリでは使用しない
export const RESTROOM_FACILITIES = {
  '1': {
    id: 1,
    name: '駅構内',
    note: 'なんば駅',
    rooms: [
      {
        id: 1,
        note: '3F南海線側',
        opening_hours_start: 14400,
        opening_hours_end: 91800,
        map_image_name: 'nanba-station_3f_nankaisen-toilet',
        stalls: [
          {placeIdHash: 'OQ9VgLr0'},
          {placeIdHash: 'WyXPv4rd'},
        ],
      },
      {
        id: 2,
        note: '3F高野線側',
        opening_hours_start: 14400,
        opening_hours_end: 91800,
        map_image_name: 'nanba-station_3f_kouyasen-toilet',
        stalls: [
          {placeIdHash: '159ez4rv'},
          {placeIdHash: 'gL94xa94'},
          {placeIdHash: '1vX2YVnQ'},
        ],
      },
      {
        id: 3,
        note: '2F中央改札',
        opening_hours_start: 14400,
        opening_hours_end: 91800,
        map_image_name: 'nanba-station_2f_chuoukaisatsu-toilet',
        stalls: [
          {placeIdHash: 'vRnlJ49E'},
          {placeIdHash: 'QL9YQO93'},
          {placeIdHash: '8oXO3GXM'},
        ],
      },
      {
        id: 4,
        note: '2F南口',
        opening_hours_start: 25200,
        opening_hours_end: 84600,
        map_image_name: 'nanba-station_2f_minamikaisatsu-toilet',
        stalls: [
          {placeIdHash: '3RnayLnM'},
          {placeIdHash: 'w4XqPRnj'},
        ],
      },
    ],
  },
}

// 時刻表リンク
export const TIME_TABLE_LINKS = [
  { station_id: 1, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/namba/n_01.pdf' },
  { station_id: 2, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shinimamiya/n_02.pdf' },
  { station_id: 2, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shinimamiya/n_01.pdf' },
  { station_id: 3, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tengachaya/n_02.pdf' },
  { station_id: 3, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tengachaya/n_01.pdf' },
  { station_id: 4, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kishinosatotamade/n_02.pdf' },
  { station_id: 4, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kishinosatotamade/n_01.pdf' },
  { station_id: 5, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kohama/n_02.pdf' },
  { station_id: 5, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kohama/n_01.pdf' },
  { station_id: 6, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sumiyoshitaisha/n_02.pdf' },
  { station_id: 6, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sumiyoshitaisha/n_01.pdf' },
  { station_id: 7, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/suminoe/n_02.pdf' },
  { station_id: 7, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/suminoe/n_01.pdf' },
  { station_id: 8, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shichido/n_02.pdf' },
  { station_id: 8, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shichido/n_01.pdf' },
  { station_id: 9, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sakai/n_02.pdf' },
  { station_id: 9, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sakai/n_01.pdf' },
  { station_id: 10, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/minato/n_02.pdf' },
  { station_id: 10, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/minato/n_01.pdf' },
  { station_id: 11, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/ishizugawa/n_02.pdf' },
  { station_id: 11, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/ishizugawa/n_01.pdf' },
  { station_id: 12, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/suwanomori/n_02.pdf' },
  { station_id: 12, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/suwanomori/n_01.pdf' },
  { station_id: 13, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hamaderakoen/n_02.pdf' },
  { station_id: 13, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hamaderakoen/n_01.pdf' },
  { station_id: 14, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hagoromo/n_02.pdf' },
  { station_id: 14, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hagoromo/n_01.pdf' },
  { station_id: 15, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/takaishi/n_02.pdf' },
  { station_id: 15, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/takaishi/n_01.pdf' },
  { station_id: 16, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kitasukematsu/n_02.pdf' },
  { station_id: 16, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kitasukematsu/n_01.pdf' },
  { station_id: 17, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/matsunohama/n_02.pdf' },
  { station_id: 17, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/matsunohama/n_01.pdf' },
  { station_id: 18, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/izumiotsu/n_02.pdf' },
  { station_id: 18, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/izumiotsu/n_01.pdf' },
  { station_id: 19, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tadaoka/n_02.pdf' },
  { station_id: 19, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tadaoka/n_01.pdf' },
  { station_id: 20, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/haruki/n_02.pdf' },
  { station_id: 20, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/haruki/n_01.pdf' },
  { station_id: 21, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/izumiomiya/n_02.pdf' },
  { station_id: 21, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/izumiomiya/n_01.pdf' },
  { station_id: 22, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kishiwada/n_02.pdf' },
  { station_id: 22, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kishiwada/n_01.pdf' },
  { station_id: 23, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/takojizo/n_02.pdf' },
  { station_id: 23, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/takojizo/n_01.pdf' },
  { station_id: 24, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kaizuka/n_02.pdf' },
  { station_id: 24, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kaizuka/n_01.pdf' },
  { station_id: 25, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/nishikinohama/n_02.pdf' },
  { station_id: 25, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/nishikinohama/n_01.pdf' },
  { station_id: 26, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tsuruhara/n_02.pdf' },
  { station_id: 26, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tsuruhara/n_01.pdf' },
  { station_id: 27, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/iharanosato/n_02.pdf' },
  { station_id: 27, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/iharanosato/n_01.pdf' },
  { station_id: 28, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/izumisano/n_02.pdf' },
  { station_id: 28, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/izumisano/n_01.pdf' },
  { station_id: 29, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hagurazaki/n_02.pdf' },
  { station_id: 29, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hagurazaki/n_01.pdf' },
  { station_id: 30, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/yoshiminosato/n_02.pdf' },
  { station_id: 30, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/yoshiminosato/n_01.pdf' },
  { station_id: 31, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/okadaura/n_02.pdf' },
  { station_id: 31, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/okadaura/n_01.pdf' },
  { station_id: 32, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tarui/n_02.pdf' },
  { station_id: 32, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tarui/n_01.pdf' },
  { station_id: 33, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/ozaki/n_02.pdf' },
  { station_id: 33, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/ozaki/n_01.pdf' },
  { station_id: 34, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tottorinosho/n_02.pdf' },
  { station_id: 34, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tottorinosho/n_01.pdf' },
  { station_id: 35, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hakotsukuri/n_02.pdf' },
  { station_id: 35, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hakotsukuri/n_01.pdf' },
  { station_id: 36, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tannowa/n_02.pdf' },
  { station_id: 36, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tannowa/n_01.pdf' },
  { station_id: 37, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/misakikoen/n_02.pdf' },
  { station_id: 37, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/misakikoen/n_01.pdf' },
  { station_id: 38, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kyoshi/n_02.pdf' },
  { station_id: 38, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kyoshi/n_01.pdf' },
  { station_id: 39, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/wadaimae/n_02.pdf' },
  { station_id: 39, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/wadaimae/n_01.pdf' },
  { station_id: 40, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kinokawa/n_04.pdf' },
  { station_id: 40, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kinokawa/n_01.pdf' },
  { station_id: 41, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/wakayamashi/n_02.pdf' },
  { station_id: 41, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/wakayamashi/n_04.pdf' },
  { station_id: 42, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/wakayamako/n_02.pdf' },
  { station_id: 61, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/hagoromo/n_03.pdf' },
  { station_id: 62, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kyarabashi/n_02.pdf' },
  { station_id: 62, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kyarabashi/n_01.pdf' },
  { station_id: 63, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/takashinohama/n_03.pdf' },
  { station_id: 75, direction: 'dowm', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/rinkutown/a_02.pdf' },
  { station_id: 75, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/rinkutown/a_01.pdf' },
  { station_id: 76, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/rinkutown/a_02.pdf' },
  { station_id: 76, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/rinkutown/a_01.pdf' },
  { station_id: 77, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kansaiairport/a_02.pdf' },
  { station_id: 81, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/tanagawa/n_02.pdf' },
  { station_id: 82, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/fukeko/n_02.pdf' },
  { station_id: 82, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/fukeko/n_01.pdf' },
  { station_id: 83, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/fukecho/n_02.pdf' },
  { station_id: 83, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/fukecho/n_01.pdf' },
  { station_id: 84, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/misakikoen/n_03.pdf' },
  { station_id: 88, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/higashimatsue/n_02.pdf' },
  { station_id: 88, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/higashimatsue/n_01.pdf' },
  { station_id: 89, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nakamatsue/n_02.pdf' },
  { station_id: 89, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nakamatsue/n_01.pdf' },
  { station_id: 90, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/hachimanmae/n_02.pdf' },
  { station_id: 90, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/hachimanmae/n_01.pdf' },
  { station_id: 91, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nishinosho/n_02.pdf' },
  { station_id: 91, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nishinosho/n_01.pdf' },
  { station_id: 92, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nirigahama/n_02.pdf' },
  { station_id: 92, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nirigahama/n_01.pdf' },
  { station_id: 93, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/isonoura/n_02.pdf' },
  { station_id: 93, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/isonoura/n_01.pdf' },
  { station_id: 94, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kada/n_02.pdf' },
  { station_id: 95, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/namba/k_01.pdf' },
  { station_id: 96, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/imamiyaebisu/k_02.pdf' },
  { station_id: 96, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/imamiyaebisu/k_01.pdf' },
  { station_id: 97, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shinimamiya/k_02.pdf' },
  { station_id: 97, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shinimamiya/k_01.pdf' },
  { station_id: 98, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/haginochaya/k_02.pdf' },
  { station_id: 98, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/haginochaya/k_01.pdf' },
  { station_id: 99, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tengachaya/k_02.pdf' },
  { station_id: 99, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tengachaya/k_01.pdf' },
  { station_id: 100, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kishinosatotamade/k_02.pdf' },
  { station_id: 100, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kishinosatotamade/k_01.pdf' },
  { station_id: 101, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tezukayama/k_02.pdf' },
  { station_id: 101, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/tezukayama/k_01.pdf' },
  { station_id: 102, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sumiyoshihigashi/k_02.pdf' },
  { station_id: 102, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sumiyoshihigashi/k_01.pdf' },
  { station_id: 103, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sawanocho/k_02.pdf' },
  { station_id: 103, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sawanocho/k_01.pdf' },
  { station_id: 104, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/abikomae/k_02.pdf' },
  { station_id: 104, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/abikomae/k_01.pdf' },
  { station_id: 105, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/asakayama/k_02.pdf' },
  { station_id: 105, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/asakayama/k_01.pdf' },
  { station_id: 106, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sakaihigashi/k_02.pdf' },
  { station_id: 106, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sakaihigashi/k_01.pdf' },
  { station_id: 107, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mikunigaoka/k_02.pdf' },
  { station_id: 107, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mikunigaoka/k_01.pdf' },
  { station_id: 108, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mozuhachiman/k_02.pdf' },
  { station_id: 108, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mozuhachiman/k_01.pdf' },
  { station_id: 109, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/nakamozu/k_02.pdf' },
  { station_id: 109, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nakamozu/k_04.pdf' },
  { station_id: 110, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shirasagi/k_02.pdf' },
  { station_id: 110, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/shirasagi/k_01.pdf' },
  { station_id: 111, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hatsushiba/k_02.pdf' },
  { station_id: 111, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hatsushiba/k_01.pdf' },
  { station_id: 112, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hagiharatenjin/k_02.pdf' },
  { station_id: 112, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hagiharatenjin/k_01.pdf' },
  { station_id: 113, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kitanoda/k_02.pdf' },
  { station_id: 113, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kitanoda/k_01.pdf' },
  { station_id: 114, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sayama/k_02.pdf' },
  { station_id: 114, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/sayama/k_01.pdf' },
  { station_id: 115, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/osakasayamashi/k_02.pdf' },
  { station_id: 115, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/osakasayamashi/k_01.pdf' },
  { station_id: 116, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kongo/k_02.pdf' },
  { station_id: 116, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kongo/k_01.pdf' },
  { station_id: 117, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/takidani/k_02.pdf' },
  { station_id: 117, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/takidani/k_01.pdf' },
  { station_id: 118, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/chiyoda/k_02.pdf' },
  { station_id: 118, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/chiyoda/k_01.pdf' },
  { station_id: 119, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kawachinagano/k_02.pdf' },
  { station_id: 119, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kawachinagano/k_01.pdf' },
  { station_id: 120, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mikkaichicho/k_02.pdf' },
  { station_id: 120, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mikkaichicho/k_01.pdf' },
  { station_id: 121, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mikanodai/k_02.pdf' },
  { station_id: 121, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/mikanodai/k_01.pdf' },
  { station_id: 122, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/chihayaguchi/k_02.pdf' },
  { station_id: 122, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/chihayaguchi/k_01.pdf' },
  { station_id: 123, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/amami/k_02.pdf' },
  { station_id: 123, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/amami/k_01.pdf' },
  { station_id: 124, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kimitoge/k_02.pdf' },
  { station_id: 124, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/kimitoge/k_01.pdf' },
  { station_id: 125, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/rinkandenentoshi/k_02.pdf' },
  { station_id: 125, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/rinkandenentoshi/k_01.pdf' },
  { station_id: 126, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/miyukitsuji/k_02.pdf' },
  { station_id: 126, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/miyukitsuji/k_01.pdf' },
  { station_id: 127, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hashimoto/k_02.pdf' },
  { station_id: 127, direction: 'down', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/hashimoto/k_01.pdf' },
  { station_id: 128, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kiishimizu/k_02.pdf' },
  { station_id: 128, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kiishimizu/k_01.pdf' },
  { station_id: 129, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kamuro/k_02.pdf' },
  { station_id: 129, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kamuro/k_01.pdf' },
  { station_id: 130, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kudoyama/k_02.pdf' },
  { station_id: 130, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kudoyama/k_01.pdf' },
  { station_id: 131, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/koyashita/k_02.pdf' },
  { station_id: 131, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/koyashita/k_01.pdf' },
  { station_id: 132, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/shimokosawa/k_02.pdf' },
  { station_id: 132, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/shimokosawa/k_01.pdf' },
  { station_id: 133, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kamikosawa/k_02.pdf' },
  { station_id: 133, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kamikosawa/k_01.pdf' },
  { station_id: 134, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kiihosokawa/k_02.pdf' },
  { station_id: 134, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kiihosokawa/k_01.pdf' },
  { station_id: 135, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kiikamiya/k_02.pdf' },
  { station_id: 135, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kiikamiya/k_01.pdf' },
  { station_id: 136, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/gokurakubashi/k_02.pdf' },
  { station_id: 137, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/shiomibashi/k_02.pdf' },
  { station_id: 138, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/ashiharacho/k_01.pdf' },
  { station_id: 138, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/ashiharacho/k_02.pdf' },
  { station_id: 139, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kizugawa/k_01.pdf' },
  { station_id: 139, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kizugawa/k_02.pdf' },
  { station_id: 140, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/tsumori/k_01.pdf' },
  { station_id: 140, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/tsumori/k_02.pdf' },
  { station_id: 141, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nishitengachaya/k_01.pdf' },
  { station_id: 141, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nishitengachaya/k_02.pdf' },
  { station_id: 142, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/kishinosatotamade/k_03.pdf' },
  { station_id: 151, direction: 'up', link: 'https://www.nankai.co.jp/library/traffic/jikoku/pdf/nakamozu/k_02.pdf' },
  { station_id: 151, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/nakamozu/k_04.pdf' },
  { station_id: 152, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/fukai/s_02.pdf' },
  { station_id: 152, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/fukai/s_01.pdf' },
  { station_id: 153, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/izumigaoka/s_02.pdf' },
  { station_id: 153, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/izumigaoka/s_01.pdf' },
  { station_id: 154, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/toga_mikita/s_02.pdf' },
  { station_id: 154, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/toga_mikita/s_01.pdf' },
  { station_id: 155, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/komyoike/s_02.pdf' },
  { station_id: 155, direction: 'down', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/komyoike/s_01.pdf' },
  { station_id: 156, direction: 'up', link: 'https://www.nankai.co.jp/traffic/jikoku/pdf/izumichuo/s_02.pdf' },
  { station_id: 156, direction: 'down', link: '' },
]
